# a sufficient environment for acceptance testing
name: ipydrawio-dev

channels:
  - conda-forge
  - nodefaults

dependencies:
  ### ipydrawio-dev-deps ###

  # core
  - doit
  - nodejs >=12,!=13.*,<15
  - python # this gets patched in ci
  # run
  - ipywidgets >=7.6
  - jedi <0.18.0
  - jupyterlab >=3.0.13,<4.0.0a0
  - jupyterlab_widgets >=1
  - lxml
  - pillow
  - pypdf2
  - requests_cache
  # building
  - pip
  - twine
  - wheel
  # linting
  - black
  - flake8
  - isort >=5
  - pyflakes
  - robotframework-lint
  # unit testing
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - pytest-tornasync
  # acceptance testing
  - firefox =78
  - geckodriver >=0.28.0
  - robotframework >=4
  - robotframework-pabot
  - robotframework-seleniumlibrary
  # reporting
  - codecov

  ### ipydrawio-dev-deps ###
