#!/usr/bin/env python
from pathlib import Path
import subprocess
import sys
import shutil

doit = lambda *args: subprocess.call(["doit", *args])

doit("list", "--all", "--status")
doit("-n4")
doit("list", "--all", "--status")

SETTINGS = Path(sys.prefix) / "share/jupyter/lab/settings"
SETTINGS.mkdir(parents=True, exist_ok=True)

shutil.copy2(Path(".binder/overrides.json"), SETTINGS / "overrides.json")

sys.exit(doit())
