#!/usr/bin/env bash
set -eux

jupyter serverextension list

jupyter serverextension enable --py jupyter_videochat --sys-prefix

jupyter serverextension list

jlpm

cd drawio-export
jlpm

cd ..

jlpm clean

jlpm build

npm pack

jupyter labextension list

jupyter labextension install \
    ./jupyterlab-drawio-*.tgz \
    $(cat binder/labextensions.txt) \
    --no-build \
    --debug

jupyter lab build \
    --dev-build=False \
    --minimize=True \
    --debug

jupyter labextension list
