{% set name = "ipydrawio" %}
{% set version = "1.0.2" %}

{% set build_number = 0 %}

{% set url_base = RECIPE_DIR.replace("\\", "/") + "/../dist" %}
{% if not url_base.startswith("/") %}
{% set url_base = "/" + url_base %}
{% endif %}

package:
  name: ipydrawio-build
  version: {{ version }}

source:
  - folder: {{ name }}
    url: file://{{ url_base }}/{{ name }}-{{ version }}.tar.gz
    # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    # sha256:

  - folder: {{ name }}-export
    url: file://{{ url_base }}/{{ name }}-export-{{ version }}.tar.gz
    # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-export/{{ name }}-export-{{ version }}.tar.gz
    # sha256:

build:
  number: {{ build_number }}
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - echo "tests in outputs"

outputs:
  - name: ipydrawio
    version: {{ version }}
    build:
      number: {{ build_number }}
      noarch: python
      script:
        - cd ipydrawio && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - ipywidgets >=7.6
        - jupyterlab ==3.*
        - jupyterlab_widgets >=1
        - lxml
        - python >=3.6
    test:
      imports:
        - ipydrawio
      requires:
        - pip
        - pytest-cov
      commands:
        - pip check
        - jupyter labextension list
        - jupyter labextension list 1>labextensions 2>&1
        - cat labextensions | grep "@deathbeds/ipydrawio.*OK"  # [unix]
        - pytest -vv --pyargs ipydrawio --cov=ipydrawio --cov-fail-under=100 --cov-report=term-missing:skip-covered
    about:
      home: https://github.com/deathbeds/ipydrawio
      summary: Draw.io Diagrams as Jupyter Widgets
      license: Apache-2.0
      license_file: ipydrawio/LICENSE.txt

  - name: ipydrawio-export
    version: {{ version }}
    build:
      number: {{ build_number }}
      noarch: python
      script:
        - cd ipydrawio-export && {{ PYTHON }} -m pip install . -vv --no-deps
      entry_points:
      - jupyter-ipydrawio-export = ipydrawio_export.app:main
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - ipydrawio =={{ version }}.*
        - python >=3.6
        - pillow
        - pypdf2
        - requests_cache
        - nodejs
    test:
      imports:
        - ipydrawio_export
      requires:
        - pip
        - pytest-cov
        - pytest-tornasync
        - pytest-console-scripts
      commands:
        - pip check
        - jupyter labextension list
        - jupyter labextension list 1>labextensions 2>&1
        - cat labextensions | grep "@deathbeds/ipydrawio-pdf.*OK"  # [unix]
        - jupyter serverextension list
        - jupyter serverextension list 1>serverextensions 2>&1
        - cat serverextensions | grep "ipydrawio_export.*OK"  # [unix]
        {% set pytest_args = "--cov-fail-under=96" %}
        # TODO: investigate potential docker/locale issues upstream to restore coverage
        # {% set pytest_args = "--cov-fail-under=54 -k 'not (export_empty or export_merged or serverextension_export)'" %}  # [linux]
        - pytest -vv {{ pytest_args }} --pyargs ipydrawio_export --script-launch-mode=subprocess --cov=ipydrawio_export --cov-report=term-missing:skip-covered
    about:
      home: https://github.com/deathbeds/ipydrawio
      summary: PDF export for IPyDrawio
      license: Apache-2.0
      license_file: ipydrawio-export/LICENSE.txt

about:
  home: https://github.com/deathbeds/ipydrawio
  summary: Draw.io Diagrams as Jupyter Widgets
  license: Apache-2.0
  license_file: ipydrawio/LICENSE.txt

extra:
  feedstock-name: ipydrawio
  recipe-maintainers:
    - bollwyvl
