{% set name = "ipydrawio" %}
{% set version = "1.0.1" %}

{% set build_number = 0 %}

{% set url_base = RECIPE_DIR.replace("\\", "/") + "/../dist" %}
{% if not url_base.startswith("/") %}
{% set url_base = "/" + url_base %}
{% endif %}

package:
  name: {{ name }}-build
  version: {{ version }}

source:
  - folder: {{ name }}
    url: file://{{ url_base }}/{{ name }}-{{ version }}.tar.gz
    # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    # sha256:

  - folder: {{ name }}-export
    url: file://{{ url_base }}/{{ name }}-export-{{ version }}.tar.gz
    # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-export/{{ name }}-export-{{ version }}.tar.gz
    # sha256:

build:
  number: {{ build_number }}
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - echo "tests in outputs"

outputs:
  - name: {{ name }}
    version: {{ version }}
    build:
      number: {{ build_number }}
      noarch: python
      script:
        - cd {{ name }} && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - ipywidgets >=7.6
        - jupyterlab ==3.*
        - jupyterlab_widgets >=1
        - lxml
        - python >=3.6
    test:
      imports:
        - {{ name }}
      requires:
        - pip
        - pytest-cov
      commands:
        - pip check
        - jupyter labextension list
        - jupyter labextension list 1>labextensions 2>&1
        - cat labextensions | grep "@deathbeds/{{ name }}.*OK"  # [unix]
        - pytest -vv --pyargs {{ name }} --cov={{ name }} --cov-fail-under=100 --cov-report=term-missing:skip-covered
    about:
      home: https://github.com/deathbeds/{{ name }}
      summary: Draw.io Diagrams as Jupyter Widgets
      license: Apache-2.0
      license_file: {{ name }}/LICENSE.txt

  - name: {{ name }}-export
    version: {{ version }}
    build:
      number: {{ build_number }}
      noarch: python
      script:
        - cd {{ name }}-export && {{ PYTHON }} -m pip install . -vv --no-deps
      entry_points:
      - jupyter-{{ name }}-export = {{ name }}_export.app:main
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - {{ name }} =={{ version }}.*
        - python >=3.6
        - pillow
        - pypdf2
        - requests_cache
        - nodejs
    test:
      imports:
        - {{ name }}_export
      requires:
        - pip
        - pytest-cov
        - pytest-tornasync
        - pytest-console-scripts
      commands:
        - pip check
        - jupyter labextension list
        - jupyter labextension list 1>labextensions 2>&1
        - cat labextensions | grep "@deathbeds/{{ name }}-pdf.*OK"  # [unix]
        - jupyter serverextension list
        - jupyter serverextension list 1>serverextensions 2>&1
        - cat serverextensions | grep "{{ name }}_export.*OK"  # [unix]
        - pytest -vv --pyargs {{ name }}_export --script-launch-mode=subprocess --cov={{ name }}_export --cov-fail-under=96 --cov-report=term-missing:skip-covered
    about:
      home: https://github.com/deathbeds/{{ name }}
      summary: PDF export for IPyDrawio
      license: Apache-2.0
      license_file: {{ name }}-export/LICENSE.txt

about:
  home: https://github.com/deathbeds/{{ name }}
  summary: Draw.io Diagrams as Jupyter Widgets
  license: Apache-2.0
  license_file: {{ name }}/LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
